################################################################################
# Environment script generated by ilcsoft-install on Thu Aug 13 10:23:20 2009
# for the installation located at [ /afs/cern.ch/eng/clic/work/sailer/sl5/ilcsoft/v01-06afs ]
################################################################################

SET( ILC_HOME "/afs/cern.ch/eng/clic/work/sailer/sl5/ilcsoft/v01-06afs" CACHE PATH "Path to ILC Software" FORCE)

SET( ROOT_HOME "/afs/cern.ch/sw/lcg/app/releases/ROOT/5.22.00b/x86_64-slc5-gcc43-dbg/root" CACHE PATH "Path to ROOT" FORCE)
SET( CERNLIB_HOME "/afs/cern.ch/eng/clic/work/sailer/sl5/cernlibs/2006-g77" CACHE PATH "Path to CERNLIB" FORCE)
SET( MySQL_HOME "/afs/cern.ch/sw/lcg/external/mysql/5.0.18/slc4_amd64_gcc41" CACHE PATH "Path to MySQL" FORCE)
SET( JAVA_HOME "/afs/cern.ch/sw/lcg/external/Java/JDK/1.6.0/amd64" CACHE PATH "Path to JAVA" FORCE)
SET( CLHEP_HOME "${ILC_HOME}/CLHEP/2.0.4.2" CACHE PATH "Path to CLHEP" FORCE)
SET( GSL_HOME "${ILC_HOME}/gsl/1.8" CACHE PATH "Path to GSL" FORCE)
SET( LCIO_HOME "${ILC_HOME}/lcio/v01-11" CACHE PATH "Path to LCIO" FORCE)
SET( Marlin_HOME "${ILC_HOME}/Marlin/v00-10-04" CACHE PATH "Path to Marlin" FORCE)
SET( LCFIVertex_HOME "${ILC_HOME}/LCFIVertex/v00-03" CACHE PATH "Path to LCFIVertex" FORCE)
SET( MarlinReco_HOME "${ILC_HOME}/MarlinReco/HEAD" CACHE PATH "Path to MarlinReco" FORCE)
SET( PandoraPFA_HOME "${ILC_HOME}/PandoraPFA/v03-01" CACHE PATH "Path to PandoraPFA" FORCE)
SET( MarlinUtil_HOME "${ILC_HOME}/MarlinUtil/v00-13" CACHE PATH "Path to MarlinUtil" FORCE)
SET( GEAR_HOME "${ILC_HOME}/gear/v00-11-01" CACHE PATH "Path to GEAR" FORCE)
SET( SiliconDigi_HOME "${ILC_HOME}/SiliconDigi/v00-04-02" CACHE PATH "Path to SiliconDigi" FORCE)
SET( RAIDA_HOME "${ILC_HOME}/RAIDA/v01-04-03" CACHE PATH "Path to RAIDA" FORCE)
SET( AIDA_HOME "${RAIDA_HOME}" CACHE PATH "Path to AIDA" FORCE)
SET( CEDViewer_HOME "${ILC_HOME}/CEDViewer/v00-07" CACHE PATH "Path to CEDViewer" FORCE)
SET( Overlay_HOME "${ILC_HOME}/Overlay/v00-06-01" CACHE PATH "Path to Overlay" FORCE)
SET( MarlinTPC_HOME "${ILC_HOME}/MarlinTPC/v00-03-01" CACHE PATH "Path to MarlinTPC" FORCE)
SET( LCCD_HOME "${ILC_HOME}/lccd/v00-04" CACHE PATH "Path to LCCD" FORCE)
SET( CED_HOME "${ILC_HOME}/CED/v00-06" CACHE PATH "Path to CED" FORCE)

SET( CMAKE_MODULE_PATH "${ILC_HOME}/CMakeModules/v01-08" CACHE PATH "Path to CMakeModules" FORCE)


