*  
* $Id: bkgmode.inc,v 1.1.1.1 2005-07-11 15:15:48 aplin Exp $
*  
* $Log: not supported by cvs2svn $
* Revision 1.1.1.1  2005/06/18 10:05:35  gaede
* Initial local version
*
* Revision 1.1  2005/06/13 16:14:29  aplin
* *** empty log message ***
*
* Revision 1.1.1.1  2003/05/23 13:17:47  hvogt
* Brahms V308
*
*  
**************************************************************************
*
* set certain array sizes according to background mode.
*      1=full CCD background
*      0=all other scenarios
*
**************************************************************************
      INTEGER IFULLBKG
      PARAMETER (IFULLBKG=0)

