*  
* $Id: exxgeo.inc,v 1.1 2005-11-03 15:16:14 aplin Exp $
*  
* $Log: not supported by cvs2svn $
* Revision 1.1.1.1  2003/05/23 13:17:49  hvogt
* Brahms V308
*
*  
c --- geometrical information for extrapolations???
      REAL THXMIN,THXMAX,PHYMIN,PHYMAX
      COMMON /EXXGEO/ THXMIN,THXMAX,PHYMIN,PHYMAX
      SAVE   /EXXGEO/

*******************************************************************************
*******************************************************************************

