*  
* $Id: my_jndb.inc,v 1.1.1.1 2005-07-11 15:15:48 aplin Exp $
*  
* $Log: not supported by cvs2svn $
* Revision 1.1.1.1  2005/06/18 10:05:35  gaede
* Initial local version
*
* Revision 1.1  2005/06/13 16:14:29  aplin
* *** empty log message ***
*
* Revision 1.1.1.1  2003/05/23 13:17:49  hvogt
* Brahms V308
*
*  
      INTEGER MY_JNDBFW(NTPCOMX),MY_JNDBBW(NTPCOMX),MY_JNDBCO(NTPCOMX)
      COMMON/MY_JNDB/MY_JNDBFW,MY_JNDBBW,MY_JNDBCO

