*  
* $Id: my_tgtl.inc,v 1.1.1.1 2005-07-11 15:15:48 aplin Exp $
*  
* $Log: not supported by cvs2svn $
* Revision 1.1.1.1  2005/06/18 10:05:35  gaede
* Initial local version
*
* Revision 1.1  2005/06/13 16:14:29  aplin
* *** empty log message ***
*
* Revision 1.1.1.1  2003/05/23 13:17:48  hvogt
* Brahms V308
*
*  
       INTEGER MY_JTGTIO,MY_JTGTN1,MY_JTGTNR
       COMMON/MY_TGTL/MY_JTGTIO(MAXCND),
     &                MY_JTGTN1(MAXCND),MY_JTGTNR(MAXCND)

