*  
* $Id: tarcjj.inc,v 1.1.1.1 2005-07-11 15:15:48 aplin Exp $
*  
* $Log: not supported by cvs2svn $
* Revision 1.1.1.1  2005/06/18 10:05:35  gaede
* Initial local version
*
* Revision 1.1  2005/06/13 16:14:29  aplin
* *** empty log message ***
*
* Revision 1.1.1.1  2003/05/23 13:17:49  hvogt
* Brahms V308
*
*  
      INTEGER JTARIR,JTARTL,JTARP0,JTARD0,JTARZ0,JTARC1,JTARC2,JTARER,
     +          JTARPI,JTAROF,JTARNC,JTARAN,JTARTN,LTARCA
      PARAMETER(JTARIR=1,JTARTL=2,JTARP0=3,JTARD0=4,JTARZ0=5,JTARC1=6,
     +          JTARC2=7,JTARER=8,JTARPI=13,JTAROF=14,JTARNC=15,
     +          JTARAN=16,JTARTN=17,LTARCA=17)

