*  
* $Id: tchajj.inc,v 1.1.1.1 2005-07-11 15:15:48 aplin Exp $
*  
* $Log: not supported by cvs2svn $
* Revision 1.1.1.1  2005/06/18 10:05:35  gaede
* Initial local version
*
* Revision 1.1  2005/06/13 16:14:29  aplin
* *** empty log message ***
*
* Revision 1.1.1.1  2003/05/23 13:17:48  hvogt
* Brahms V308
*
*  
      INTEGER JTCHIR,JTCHTL,JTCHP0,JTCHD0,JTCHZ0,JTCHLC,JTCHC1,JTCHC2,
     +          JTCHER,JTCHPI,JTCHOF,JTCHNC,LTCHAA
      PARAMETER(JTCHIR=1,JTCHTL=2,JTCHP0=3,JTCHD0=4,JTCHZ0=5,JTCHLC=6,
     +          JTCHC1=7,JTCHC2=8,JTCHER=9,JTCHPI=24,JTCHOF=25,
     +          JTCHNC=26,LTCHAA=26)

