.PHONY: lib clean

clean:
	@echo ""
	@echo "*******************************************"
	@echo "*          cleaning MarlinReco ...        *"
	@echo "*******************************************"
	@echo ""
	@$(MAKE) -C .. clean


lib:
	@echo ""
	@echo "*******************************************"
	@echo "*          building MarlinReco ...        *"
	@echo "*******************************************"
	@echo ""
	@$(MAKE) -C .. 

