######################################################
#
# Makefile to build MarlinReco
#
# @author Frank Gaede, DESY
# @author Jan Engels, DESY
#
######################################################

.PHONY: all lib doc clean distclean

all: lib

lib:
	$(MAKE) -C ../ lib

doc:
	$(MAKE) -C ../ doc

clean:
	$(MAKE) -C ../ clean

distclean:
	$(MAKE) -C ../ distclean

# end
